theme: minima
title: Mambee - Fábrica Escola de Sofware do IFPI Campus Picos
email: mambee@ifpi.edu.br
author:
description: Fábrica Escola de Sofware do IFPI Campus Picos.
baseurl: ""
twitter_username: mambeeifpi
github_username:  mambeedev
